// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcaDcc4nyl7biwQYUdnCwIxE_ARFPQNu0',
    appId: '1:746202682120:web:bd6d246dfc6d73039d52bd',
    messagingSenderId: '746202682120',
    projectId: 'cosmira-5b2b4',
    authDomain: 'cosmira-5b2b4.firebaseapp.com',
    storageBucket: 'cosmira-5b2b4.firebasestorage.app',
    measurementId: 'G-NZTDKDXKWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA44v3esLYuqN8eJ7-7hAz0vak3z9HDgKc',
    appId: '1:746202682120:android:305c19bca6f3af9f9d52bd',
    messagingSenderId: '746202682120',
    projectId: 'cosmira-5b2b4',
    storageBucket: 'cosmira-5b2b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzIjLeWIvXMs1ILHmJx6dEf_K-iT93q2U',
    appId: '1:746202682120:ios:fa6c4b4045089ed29d52bd',
    messagingSenderId: '746202682120',
    projectId: 'cosmira-5b2b4',
    storageBucket: 'cosmira-5b2b4.firebasestorage.app',
    iosBundleId: 'com.example.cosmira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzIjLeWIvXMs1ILHmJx6dEf_K-iT93q2U',
    appId: '1:746202682120:ios:fa6c4b4045089ed29d52bd',
    messagingSenderId: '746202682120',
    projectId: 'cosmira-5b2b4',
    storageBucket: 'cosmira-5b2b4.firebasestorage.app',
    iosBundleId: 'com.example.cosmira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcaDcc4nyl7biwQYUdnCwIxE_ARFPQNu0',
    appId: '1:746202682120:web:63cfd6d88b1cff739d52bd',
    messagingSenderId: '746202682120',
    projectId: 'cosmira-5b2b4',
    authDomain: 'cosmira-5b2b4.firebaseapp.com',
    storageBucket: 'cosmira-5b2b4.firebasestorage.app',
    measurementId: 'G-K1D6HS7LKV',
  );
}
